package org.stark.settersmith.actions;

import com.intellij.notification.Notification;
import com.intellij.notification.NotificationType;
import com.intellij.notification.Notifications;
import com.intellij.openapi.actionSystem.ActionUpdateThread;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;
import com.intellij.openapi.actionSystem.CommonDataKeys;
import com.intellij.openapi.command.WriteCommandAction;
import com.intellij.openapi.editor.Document;
import com.intellij.openapi.editor.Editor;
import com.intellij.openapi.progress.ProgressIndicator;
import com.intellij.openapi.progress.ProgressManager;
import com.intellij.openapi.progress.Task;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.util.TextRange;
import com.intellij.psi.*;
import com.intellij.psi.util.PsiTreeUtil;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Stream;

/**
 * This class represents an IntelliJ IDEA action that automates the generation of setter method
 * calls for a specific target variable within a given method. It analyzes the current editor
 * context to infer the necessary elements such as the target variable, its type's class, and the
 * enclosing method, then inserts appropriate setter method calls to the method body.
 */
public class GenerateSetterAction extends AnAction {

  /**
   * Logger instance used for logging messages and reporting errors or debug information related to
   * the execution of the {@link GenerateSetterAction} class methods.
   * <p>
   * This logger helps to capture and record critical application events such as: - Errors during
   * the addition of setter calls (`addSetterCallsToMethod`). - Failures while modifying method
   * signatures (`addMissingParametersToMethodSignature`). - Other exceptional or important events
   * in the execution flow.
   * <p>
   * Logs are primarily useful for debugging and monitoring the correctness of the plugin
   * functionality during runtime.
   * <p>
   * The Logger is instantiated using the {@link LoggerFactory} with the class name
   * {@code GenerateSetterAction} to provide contextual logs specific to this class's execution.
   */
  private static final Logger LOG = LoggerFactory.getLogger(GenerateSetterAction.class);
  /**
   * Represents the identifier for the notification group used by this action, typically for
   * displaying user notifications through the IntelliJ Platform's notification system.
   * <p>
   * This constant is utilized within the `showNotification` method to categorize notifications
   * generated by the "Generate Setter Action" functionality.
   */
  private static final String NOTIFICATION_GROUP = "SetterSmith.Notifications";

  /**
   * Determines the proper thread on which this action should be updated.
   *
   * @return the thread on which this action should be updated, specifically the background thread.
   */
  @Override
  public @NotNull ActionUpdateThread getActionUpdateThread() {
    // Specify that this action requires running on the Event Dispatch Thread
    return ActionUpdateThread.BGT;
  }

  /**
   * Performs an action invoked by an {@code AnActionEvent}. This method generates and inserts
   * setter method calls for a specific target variable in the current context, considering the
   * enclosing method and class. The processing is performed in a background task to enhance
   * performance and avoid blocking the user interface thread.
   *
   * @param event an instance of {@code AnActionEvent} that provides context and data about the
   *              action being executed, such as the project, editor, and PSI file in the current
   *              context.
   */
  @Override
  public void actionPerformed(AnActionEvent event) {
    Project project = event.getProject();
    Editor editor = event.getData(CommonDataKeys.EDITOR);
    PsiFile psiFile = event.getData(CommonDataKeys.PSI_FILE);
    if (!validateContext(project, editor, psiFile)) {
      return;
    }

    PsiElement elementAtCaret = getRelevantElementAtCaret(editor, psiFile);
    if (elementAtCaret == null) {
      showNotification(project, "No element found at caret.", NotificationType.ERROR);
      return;
    }

    PsiVariable targetVariable = PsiTreeUtil.getParentOfType(elementAtCaret, PsiVariable.class);
    PsiClass variableClass = resolveClassFromType(
        targetVariable != null ? targetVariable.getType() : null);
    PsiMethod enclosingMethod = PsiTreeUtil.getParentOfType(elementAtCaret, PsiMethod.class);

    if (targetVariable == null || variableClass == null || enclosingMethod == null) {
      showNotification(project, "Invalid selection context.", NotificationType.ERROR);
      return;
    }

    ProgressManager.getInstance()
        .run(new Task.Backgroundable(project, "Generating setter method calls...", false) {
          @Override
          public void run(@NotNull ProgressIndicator indicator) {
            WriteCommandAction.runWriteCommandAction(project,
                () -> addSetterCallsToMethod(project, editor, enclosingMethod, targetVariable,
                    variableClass));
            showNotification(project, "Setter method calls added.", NotificationType.INFORMATION);
          }
        });
  }

  /**
   * Retrieves the relevant PSI element located at the caret position within the editor. Uses the
   * offset of the caret to find the corresponding element in the PSI file. If the element at the
   * caret is a white space or a Java token, it adjusts the offset to retrieve the preceding
   * element.
   *
   * @param editor  the editor instance to retrieve the caret position information from
   * @param psiFile the PSI file instance containing the code structure to locate the element
   *                within
   * @return the relevant PSI element at the caret position, or the preceding element if the one at
   * the caret is non-relevant
   */
  private PsiElement getRelevantElementAtCaret(Editor editor, PsiFile psiFile) {
    int offset = editor.getCaretModel().getOffset();
    PsiElement elementAtCaret = psiFile.findElementAt(offset);
    return (elementAtCaret instanceof PsiWhiteSpace || elementAtCaret instanceof PsiJavaToken)
        ? psiFile.findElementAt(Math.max(0, offset - 1))
        : elementAtCaret;
  }

  /**
   * Adds setter method calls for a specified variable within a given method. This method identifies
   * all setter methods in the provided variable's class, generates calls for these setters with
   * appropriate parameters, and inserts them into the body of the enclosing method. Additionally,
   * it ensures any new parameters required by the setter calls are added to the method signature.
   *
   * @param project         the current project context, used for interacting with the IntelliJ
   *                        platform APIs
   * @param editor          the editor instance where the method modifications are performed
   * @param enclosingMethod the method in which setter calls are to be inserted
   * @param targetVariable  the variable for which setter method calls are to be generated
   * @param variableClass   the class type of the target variable, from which setter methods are
   *                        identified
   */
  private void addSetterCallsToMethod(Project project, Editor editor, PsiMethod enclosingMethod,
      PsiVariable targetVariable, PsiClass variableClass) {
    PsiCodeBlock methodBody = enclosingMethod.getBody();
    if (methodBody == null) {
      return;
    }

    PsiElementFactory elementFactory = JavaPsiFacade.getElementFactory(project);
    Map<String, String> collectedParameters = new LinkedHashMap<>();

    // Collect all parameters from the methods
    List<String> setterCalls = Stream.of(variableClass.getMethods())
        .filter(m -> m.getName().startsWith("set"))
        .map(m -> createSetterCallForMethod(m, targetVariable.getName(), collectedParameters))
        .flatMap(List::stream)
        .toList();

    try {
      Document document = getDocument(editor, setterCalls);
      PsiDocumentManager.getInstance(project).commitDocument(document);
    } catch (Exception ex) {
      LOG.error("Failed to insert call statement", ex);
      showNotification(project, "Failed to insert call statement", NotificationType.ERROR);
    }

    addMissingParametersToMethodSignature(project, enclosingMethod, collectedParameters,
        elementFactory);
  }

  /**
   * Inserts generated setter method calls into the current editor document. The method determines
   * the indentation of the current line, appends setter calls with the matching indentation, and
   * inserts the text at the end of the current line.
   *
   * @param editor the editor instance where the text modifications are made
   * @param call   a list of setter method call strings to be inserted into the document
   * @return the updated document after the setter calls are inserted
   */
  private static @NotNull Document getDocument(Editor editor, List<String> call) {
    Document document = editor.getDocument();
    int currentCaretOffset = editor.getCaretModel().getOffset();
    int currentLineNumber = document.getLineNumber(currentCaretOffset);
    int lineEndOffset = document.getLineEndOffset(currentLineNumber);
    String lineSeparator = "\n";
    // Extract the current line's text to determine its indentation.
    String currentLineText = document.getText(
        new TextRange(document.getLineStartOffset(currentLineNumber), lineEndOffset));
    // Use regex to capture leading whitespace.
    String currentIndentation = "";
    if (!currentLineText.isEmpty()) {
      currentIndentation = currentLineText.replaceAll("^(\\s*).*$", "$1");
    }

    StringBuilder insertedTextBuilder = new StringBuilder();
    insertedTextBuilder.append(lineSeparator);
    for (String callStmt : call) {
      insertedTextBuilder.append(currentIndentation)
          .append(callStmt)
          .append(lineSeparator);
    }
    String insertionText = insertedTextBuilder.toString();
    document.insertString(lineEndOffset, insertionText);
    return document;
  }

  /**
   * Generates a list containing a setter method call for a given method and variable name. Also
   * updates the provided parameter map with the parameter name and type associated with the setter
   * method.
   *
   * @param method       the setter method for which the call string needs to be generated
   * @param variableName the name of the variable on which the setter method should be called
   * @param parameterMap a map where the method's parameter name and its type will be stored, if not
   *                     already present
   * @return a list containing a single string representing the setter method call
   */
  private List<String> createSetterCallForMethod(PsiMethod method, String variableName,
      Map<String, String> parameterMap) {
    String paramName =
        Character.toLowerCase(method.getName().charAt(3)) + method.getName().substring(4);
    String paramType = method.getParameterList().getParameters()[0].getType().getCanonicalText();

    parameterMap.putIfAbsent(paramName, paramType);

    String call = String.format("%s.%s(%s);", variableName, method.getName(), paramName);
    return List.of(call);
  }

  /**
   * Adds missing parameters to the signature of the provided method if they do not already exist.
   * Iterates through the map of new parameters, checks if each parameter is already present in the
   * method's parameter list, and adds the missing ones using the specified element factory. Errors
   * during the addition process are logged, and a notification is displayed in the project.
   *
   * @param project         the current project context, used to show notifications and access
   *                        project-specific APIs
   * @param enclosingMethod the method whose parameter list will be updated with the new parameters
   * @param newParameters   a map of parameter names to their types that need to be added to the
   *                        method signature
   * @param elementFactory  a factory used to create new PSI elements, such as parameter objects
   */
  private void addMissingParametersToMethodSignature(Project project, PsiMethod enclosingMethod,
      Map<String, String> newParameters, PsiElementFactory elementFactory) {
    PsiParameterList existingParameters = enclosingMethod.getParameterList();

    newParameters.forEach((name, type) -> {
      boolean parameterExists = Arrays.stream(existingParameters.getParameters())
          .anyMatch(param -> param.getName().equals(name));

      if (!parameterExists) {
        try {
          existingParameters.add(createParameter(type, name, elementFactory));
        } catch (Exception ex) {
          LOG.error("Failed to add parameter to method", ex);
          showNotification(project, "Failed to add parameter to method", NotificationType.ERROR);
        }
      }
    });
  }

  /**
   * Creates a PSI parameter element based on the given type and name. This method uses the
   * specified element factory to create the parameter by combining the type and name into a
   * parameter declaration format.
   *
   * @param type           the data type of the parameter to be created
   * @param name           the name of the parameter to be created
   * @param elementFactory the factory used to create the parameter element
   * @return a PSI parameter element representing the created parameter
   */
  private PsiParameter createParameter(String type, String name, PsiElementFactory elementFactory) {
    return elementFactory.createParameterFromText(type + " " + name, null);
  }

  /**
   * Resolves and retrieves a {@code PsiClass} from the given {@code PsiType}. If the type is an
   * instance of {@code PsiClassType}, it attempts to resolve the underlying class. Otherwise, it
   * returns {@code null}.
   *
   * @param type the {@code PsiType} from which the {@code PsiClass} is to be resolved
   * @return the resolved {@code PsiClass} object if the type is a {@code PsiClassType}, or
   * {@code null} if the type is not a {@code PsiClassType} or cannot be resolved
   */
  private PsiClass resolveClassFromType(PsiType type) {
    return type instanceof PsiClassType ? ((PsiClassType) type).resolve() : null;
  }

  /**
   * Displays a notification within the IntelliJ IDE. This method uses the Notifications API to show
   * a notification with the specified message and type, and optionally associates it with the
   * provided project.
   *
   * @param project the current project context in which the notification should be displayed. Can
   *                be null if the notification is not tied to a specific project.
   * @param message the content of the notification to be displayed.
   * @param type    the type of the notification, which determines its appearance and severity
   *                (e.g., information, warning, error).
   */
  private void showNotification(@Nullable Project project, String message, NotificationType type) {
    Notifications.Bus.notify(
        new Notification(NOTIFICATION_GROUP, "Setter generator plugin", message, type), project);
  }

  /**
   * Validates the current context by checking if the project, editor, and PSI file are not null. If
   * any of these are null, a notification is displayed and the method returns false.
   *
   * @param project the current project context, used for showing notifications
   * @param editor  the editor instance to validate
   * @param psiFile the PSI file instance to validate
   * @return true if all parameters (project, editor, and psiFile) are not null, false otherwise
   */
  private boolean validateContext(Project project, Editor editor, PsiFile psiFile) {
    if (project == null || editor == null || psiFile == null) {
      showNotification(project, "No project or editor or file open.", NotificationType.ERROR);
      return false;
    }
    return true;
  }

  /**
   * Updates the presentation of the associated action in the IntelliJ platform UI. Sets the action
   * as both enabled and visible, allowing it to be interacted with in the context in which it is
   * displayed.
   *
   * @param e the event holding context and data for the action update, including presentation and
   *          other components related to the action's appearance and behavior
   */
  @Override
  public void update(AnActionEvent e) {
    e.getPresentation().setEnabledAndVisible(true);
  }
}